#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 250

#define ONESHOT_TAP_TOGGLE 2

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "05GrK/OazLLJ"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 1

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

